version: '3'

services:

  top_up_api:
    build:
      context: .
      dockerfile: ./TopUpService.Dockerfile
    image: top-up-api:latest
    container_name: top_up_api
    ports:
    - 8080:8080
    networks:
    - backend-network
    depends_on: 
    - db
    - rabbit_mq
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - CONNECTION_STRING=Host=db;Username=some_user;Password=Example@Bad@Password!123;Database=topup_db
    - RABBIT_MQ_HOST=rabbit_mq
    - RABBIT_MQ_USER=guest
    - RABBIT_MQ_PASS=guest
    - ACCOUNT_API_BASE_ADDRESS=http://account_api
    - ACCOUNT_API_PORT=8082

  account_api:
    build:
      context: .
      dockerfile: ./AccountService.Dockerfile
    image: account-api:latest
    container_name: account_api
    ports:
    - 8082:8082
    networks:
    - backend-network
    depends_on: 
    - db
    - rabbit_mq
    environment:
    - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: postgres:latest
    container_name: topup_db
    environment:
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: Example@Bad@Password!123
      POSTGRES_DB: topup_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - backend-network

  rabbit_mq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
    - backend-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
    backend-network:
        driver: bridge
